name: Crear un informe
description: Crea un informe de errores para ayudarnos a mejorar.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to fill out a bug report. Remember to fill out all fields including the title above.
        Una cuestión que no se rellene correctamente se cerrará.
  - type: dropdown
    id: client
    attributes:
      label: "¿Con qué cliente juegas?"
      options:
      - enGB
      - enUS
      - deDE
      - esES
      - esMX
      - frFR
      - ruRU
      - Otro
    validations:
      required: true
  - type: checkboxes
    id: faction
    attributes:
      label: "Facción"
      description: |
        ¿En que facción te ocurrió el error?
      options:
      - label: Alianza
      - label: Horda
  - type: checkboxes
    id: phase
    attributes:
      label: "Fase de contenido"
      description: |
        Solo seleccione la opción de genérico, en caso de que influya en todas las fases del juego.
      options:
      - label: Generico
      - label: 1-19
      - label: 20-29
      - label: 30-39
      - label: 40-49
      - label: 50-59
      - label: Otro
  - type: textarea
    id: current
    attributes:
      label: "Comportamiento actual"
      description: |
        Describe el error en detalle. Base de datos para enlazar hechizos, NPCs, misiones, etc: https://wowgaming.altervista.org/aowow/
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Comportamiento esperado de Blizzlike"
      description: |
        Describe cómo debería funcionar sin el bug. Enlaza con pruebas si es posible, como vídeos de YouTube o comentarios de WoWHead de la época.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: "Fuente"
      description: |
        HEADS UP: include sources in your bug report which are relevant to the 3.3.5a game version, cerraremos cualquier error del tipo "X debería cambiarse por Y" reportado sin fuentes.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: "Pasos para reproducir el problema"
      description: |
        Describa con precisión cómo reproducir el error para que podamos solucionarlo o confirmar su existencia:
        - ¿Qué comandos utilizar? ¿A qué NPC teletransportarse?
        - ¿Necesitamos tener banderas de depuración en Cmake?
        - ¿Necesitamos mirar la consola mientras se produce el fallo?
        - Otros pasos
        - Utiliza los comandos ingame para identificar el GUID único de un mineral/herb/npc: .npc info / .gobject near
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: "Notas adicionales"
      description: |
        Cualquier información que pueda ayudar a los desarrolladores a identificar y solucionar el problema debe ponerse aquí.
        Ejemplos:
        Enlaces a objetos/NPCs/misiones de https://wowgaming.altervista.org/aowow/
      placeholder: |
        Ninguno
    validations:
      required: false
  - type: textarea
    id: commit
    attributes:
      label: "AC rev. hash/commit"
      value: |
        https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: "Sistema operativo"
      value: |
        Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    id: modules
    attributes:
      label: "Modulos"
      value: |
        - [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
        - [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
        - [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
        - [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
        - [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
        - [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
        - [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
        - [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
        - [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
        - [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
        - [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
        - [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
        - [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
        - [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
        - [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
        - [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
        - [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
        - [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
        - [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
        - [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    validations:
      required: false
  - type: textarea
    id: customizations
    attributes:
      label: "Personalizaciones"
      value: |
        None
    validations:
      required: false
  - type: textarea
    id: server
    attributes:
      label: "Servidor"
      value: |
        ChromieCraft
    validations:
      required: false
